version: '3'

services:
  manga_service:
      
    build:
      context: .
      dockerfile: Dockerfile
    container_name: manga_service
    networks:
      - manga_network
    # ports:
    #   - '3000:3000'
    environment:
      - SERVICE_TAG=${SERVICE_TAG}
      - PORT=${PORT}
      - DEBUG_MODE=${DEBUG_MODE}
      - MONGODB_DB_NAME=${MONGODB_DB_NAME}
      - MONGODB_SERVERS=${MONGODB_SERVERS}
      - MONGODB_USER=${MONGODB_USER}
      - MONGODB_PASSWORD=${MONGODB_PASSWORD}
      - RABBITMQ_BROKERS=${RABBITMQ_BROKERS}
      - RABBITMQ_USER=${RABBITMQ_USER}
      - RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD}
      - RABBITMQ_VHOST=${RABBITMQ_VHOST}
      - RABBITMQ_QUEUE_NAME=${RABBITMQ_QUEUE_NAME}
networks:
  manga_network:
    driver: bridge
